### ISSUE TITLE
Official AprilTag repo now builds with Visual Studio out of the box

### ISSUE THREAD

**Issue by biro-mark** [s-trinh/AprilTag#3]
Hi s-trinh, it looks like the official AprilTag project gained some commits that allow it to build out of the box with Visual Studio (linking against pthreads-win32) 

For example, they removed all the VLA code and replaced with malloc.
https://github.com/AprilRobotics/apriltag/commit/b6af709e0616e33b0d07e2a857b383dbb91a67ab#diff-8156605a66f73fd6619b0fa7de37a8ed

**Comment by s-trinh** [comment]
Hello Mark,

Yes, it is better to use the [original repository](https://github.com/AprilRobotics/apriltag) now.
Also, this repository is `apriltag-2016-12-01` while there is AprilTag 3 out now.

I have updated the `README` in consequence.
